# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.jira_issue import JIRAIssue  # noqa: E501
from openapi_client.rest import ApiException


class TestJIRAIssue(unittest.TestCase):
    """JIRAIssue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJIRAIssue(self):
        """Test JIRAIssue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.jira_issue.JIRAIssue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
