# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.development_environments_api import DevelopmentEnvironmentsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDevelopmentEnvironmentsApi(unittest.TestCase):
    """DevelopmentEnvironmentsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.development_environments_api.DevelopmentEnvironmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_development_environments_create(self):
        """Test case for development_environments_create

        """
        pass

    def test_development_environments_list(self):
        """Test case for development_environments_list

        """
        pass

    def test_development_environments_partial_update(self):
        """Test case for development_environments_partial_update

        """
        pass

    def test_development_environments_read(self):
        """Test case for development_environments_read

        """
        pass

    def test_development_environments_update(self):
        """Test case for development_environments_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
