# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.jira_finding_mappings_api import JiraFindingMappingsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestJiraFindingMappingsApi(unittest.TestCase):
    """JiraFindingMappingsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.jira_finding_mappings_api.JiraFindingMappingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_jira_finding_mappings_create(self):
        """Test case for jira_finding_mappings_create

        """
        pass

    def test_jira_finding_mappings_delete(self):
        """Test case for jira_finding_mappings_delete

        """
        pass

    def test_jira_finding_mappings_list(self):
        """Test case for jira_finding_mappings_list

        """
        pass

    def test_jira_finding_mappings_partial_update(self):
        """Test case for jira_finding_mappings_partial_update

        """
        pass

    def test_jira_finding_mappings_read(self):
        """Test case for jira_finding_mappings_read

        """
        pass

    def test_jira_finding_mappings_update(self):
        """Test case for jira_finding_mappings_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
