# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.notes_api import NotesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestNotesApi(unittest.TestCase):
    """NotesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.notes_api.NotesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_notes_list(self):
        """Test case for notes_list

        """
        pass

    def test_notes_partial_update(self):
        """Test case for notes_partial_update

        """
        pass

    def test_notes_read(self):
        """Test case for notes_read

        """
        pass

    def test_notes_update(self):
        """Test case for notes_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
