# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.metadata_api import MetadataApi  # noqa: E501
from openapi_client.rest import ApiException


class TestMetadataApi(unittest.TestCase):
    """MetadataApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.metadata_api.MetadataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_metadata_create(self):
        """Test case for metadata_create

        """
        pass

    def test_metadata_delete(self):
        """Test case for metadata_delete

        """
        pass

    def test_metadata_list(self):
        """Test case for metadata_list

        """
        pass

    def test_metadata_partial_update(self):
        """Test case for metadata_partial_update

        """
        pass

    def test_metadata_read(self):
        """Test case for metadata_read

        """
        pass

    def test_metadata_update(self):
        """Test case for metadata_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
