# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.tool_configurations_api import ToolConfigurationsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestToolConfigurationsApi(unittest.TestCase):
    """ToolConfigurationsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.tool_configurations_api.ToolConfigurationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tool_configurations_create(self):
        """Test case for tool_configurations_create

        """
        pass

    def test_tool_configurations_delete(self):
        """Test case for tool_configurations_delete

        """
        pass

    def test_tool_configurations_list(self):
        """Test case for tool_configurations_list

        """
        pass

    def test_tool_configurations_partial_update(self):
        """Test case for tool_configurations_partial_update

        """
        pass

    def test_tool_configurations_read(self):
        """Test case for tool_configurations_read

        """
        pass

    def test_tool_configurations_update(self):
        """Test case for tool_configurations_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
