# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.product_types_api import ProductTypesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestProductTypesApi(unittest.TestCase):
    """ProductTypesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.product_types_api.ProductTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_product_types_create(self):
        """Test case for product_types_create

        """
        pass

    def test_product_types_generate_report(self):
        """Test case for product_types_generate_report

        """
        pass

    def test_product_types_list(self):
        """Test case for product_types_list

        """
        pass

    def test_product_types_partial_update(self):
        """Test case for product_types_partial_update

        """
        pass

    def test_product_types_read(self):
        """Test case for product_types_read

        """
        pass

    def test_product_types_update(self):
        """Test case for product_types_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
