# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ProductType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'critical_product': 'bool',
        'key_product': 'bool',
        'updated': 'datetime',
        'created': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'critical_product': 'critical_product',
        'key_product': 'key_product',
        'updated': 'updated',
        'created': 'created'
    }

    def __init__(self, id=None, name=None, critical_product=None, key_product=None, updated=None, created=None):  # noqa: E501
        """ProductType - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._name = None
        self._critical_product = None
        self._key_product = None
        self._updated = None
        self._created = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        if critical_product is not None:
            self.critical_product = critical_product
        if key_product is not None:
            self.key_product = key_product
        if updated is not None:
            self.updated = updated
        if created is not None:
            self.created = created

    @property
    def id(self):
        """Gets the id of this ProductType.  # noqa: E501


        :return: The id of this ProductType.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProductType.


        :param id: The id of this ProductType.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ProductType.  # noqa: E501


        :return: The name of this ProductType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProductType.


        :param name: The name of this ProductType.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 255:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def critical_product(self):
        """Gets the critical_product of this ProductType.  # noqa: E501


        :return: The critical_product of this ProductType.  # noqa: E501
        :rtype: bool
        """
        return self._critical_product

    @critical_product.setter
    def critical_product(self, critical_product):
        """Sets the critical_product of this ProductType.


        :param critical_product: The critical_product of this ProductType.  # noqa: E501
        :type: bool
        """

        self._critical_product = critical_product

    @property
    def key_product(self):
        """Gets the key_product of this ProductType.  # noqa: E501


        :return: The key_product of this ProductType.  # noqa: E501
        :rtype: bool
        """
        return self._key_product

    @key_product.setter
    def key_product(self, key_product):
        """Sets the key_product of this ProductType.


        :param key_product: The key_product of this ProductType.  # noqa: E501
        :type: bool
        """

        self._key_product = key_product

    @property
    def updated(self):
        """Gets the updated of this ProductType.  # noqa: E501


        :return: The updated of this ProductType.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this ProductType.


        :param updated: The updated of this ProductType.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    @property
    def created(self):
        """Gets the created of this ProductType.  # noqa: E501


        :return: The created of this ProductType.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this ProductType.


        :param created: The created of this ProductType.  # noqa: E501
        :type: datetime
        """

        self._created = created

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
