# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class TestType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'tags': 'list[str]',
        'name': 'str',
        'static_tool': 'bool',
        'dynamic_tool': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'tags': 'tags',
        'name': 'name',
        'static_tool': 'static_tool',
        'dynamic_tool': 'dynamic_tool'
    }

    def __init__(self, id=None, tags=None, name=None, static_tool=None, dynamic_tool=None):  # noqa: E501
        """TestType - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._tags = None
        self._name = None
        self._static_tool = None
        self._dynamic_tool = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if tags is not None:
            self.tags = tags
        self.name = name
        if static_tool is not None:
            self.static_tool = static_tool
        if dynamic_tool is not None:
            self.dynamic_tool = dynamic_tool

    @property
    def id(self):
        """Gets the id of this TestType.  # noqa: E501


        :return: The id of this TestType.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TestType.


        :param id: The id of this TestType.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def tags(self):
        """Gets the tags of this TestType.  # noqa: E501


        :return: The tags of this TestType.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this TestType.


        :param tags: The tags of this TestType.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def name(self):
        """Gets the name of this TestType.  # noqa: E501


        :return: The name of this TestType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TestType.


        :param name: The name of this TestType.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 200:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `200`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def static_tool(self):
        """Gets the static_tool of this TestType.  # noqa: E501


        :return: The static_tool of this TestType.  # noqa: E501
        :rtype: bool
        """
        return self._static_tool

    @static_tool.setter
    def static_tool(self, static_tool):
        """Sets the static_tool of this TestType.


        :param static_tool: The static_tool of this TestType.  # noqa: E501
        :type: bool
        """

        self._static_tool = static_tool

    @property
    def dynamic_tool(self):
        """Gets the dynamic_tool of this TestType.  # noqa: E501


        :return: The dynamic_tool of this TestType.  # noqa: E501
        :rtype: bool
        """
        return self._dynamic_tool

    @dynamic_tool.setter
    def dynamic_tool(self, dynamic_tool):
        """Sets the dynamic_tool of this TestType.


        :param dynamic_tool: The dynamic_tool of this TestType.  # noqa: E501
        :type: bool
        """

        self._dynamic_tool = dynamic_tool

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TestType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
